from tkinter import *
from tkinter import messagebox
from PIL import ImageTk, Image
from admin.connection import MyDatabase

class cart():
    def __init__(self):
        self.wn = Tk()
        self.wn.title("Customer_Cart")
        # adding icon image
        self.img = (Image.open("C:\\store\\user_i.ico"))
        self.icoimg = ImageTk.PhotoImage(self.img)
        self.wn.iconphoto(False, self.icoimg)
        self.wn.geometry('1345x700')
        self.wn.resizable(False, False)

        self.title_photo = PhotoImage(file="C:\\store\\cartbg.png")
        self.title_photo_lable = Label(self.wn, image=self.title_photo, bd=0)
        self.title_photo_lable.image = self.title_photo
        self.title_photo_lable.place(x=0, y=0)


        self.my_label = Label(self.wn, text="FRUIT\n AND\n VEGETABLES", font=("Arial", 12), bg="#FDFC96")
        self.my_label.place(x=10, y=20)



        self.img1 = (Image.open("C:\\store\\apples.jpg"))
        self.img1 = self.img1.resize((105,80), Image.ANTIALIAS)
        self.image1 = ImageTk.PhotoImage(self.img1)
        self.label1 = Label(self.wn,image = self.image1,bg="black")
        self.label1.place(x=200,y=5)
        self.lbl1= Label (self.wn, text="     APPLE       \nRs.234 / Kg",font=("Arial",12),bg="#FDFC96")
        self.lbl1.place(x=200,y=90)


        self.img2 = Image.open("C:\\store\\Banana.jpg")
        self.img2 = self.img2.resize((105,80), Image.ANTIALIAS)
        self.image2 = ImageTk.PhotoImage(self.img2)
        self.label2 = Label(self.wn,image = self.image2,bg="black")
        self.label2.place(x=390,y=5)
        self.lbl2= Label (self.wn, text="   BANANA     \nRs.130/dozen",font=("Arial",12),bg="#FDFC96")
        self.lbl2.place(x=390,y=90)

        self.img3 = Image.open("C:\\store\\Orange.jpg")
        self.img3 = self.img3.resize((105,80), Image.ANTIALIAS)
        self.image3 = ImageTk.PhotoImage(self.img3)
        self.label3 = Label(self.wn,image = self.image3,bg="black")
        self.label3.place(x=580,y=5)
        self.lbl3= Label (self.wn, text="  ORANGE      \n Rs.250 / Kg",font=("Arial",12),bg="#FDFC96")
        self.lbl3.place(x=580,y=90)

        self.img4 = Image.open("C:\\store\\tomato.jpg")
        self.img4 = self.img4.resize((105,80), Image.ANTIALIAS)
        self.image4 = ImageTk.PhotoImage(self.img4)
        self.label4 = Label(self.wn,image = self.image4,bg="black")
        self.label4.place(x=770,y=5)
        self.lbl4= Label (self.wn, text="   TOMATO      \n Rs.50 / Kg",font=("Arial",12),bg="#FDFC96")
        self.lbl4.place(x=770,y=90)

        self.img5 = Image.open("C:\\store\\spanich.jpg")
        self.img5 = self.img5.resize((105,80), Image.ANTIALIAS)
        self.image5 = ImageTk.PhotoImage(self.img5)
        self.label5 = Label(self.wn,image = self.image5,bg="black")
        self.label5.place(x=960,y=5)
        self.lbl5= Label (self.wn, text="   SPANICH     \n Rs.60 / Kg",font=("Arial",12),bg="#FDFC96")
        self.lbl5.place(x=960,y=90)

        self.img6 = Image.open("C:\\store\\onion.jpg")
        self.img6 = self.img6.resize((105,80), Image.ANTIALIAS)
        self.image6 = ImageTk.PhotoImage(self.img6)
        self.label6 = Label(self.wn,image = self.image6,bg="black")
        self.label6.place(x=1150,y=5)
        self.lbl6= Label (self.wn, text="    ONION        \n Rs.80 / Kg",font=("Arial",12),bg="#FDFC96")
        self.lbl6.place(x=1150,y=90)

        self.my_label= Label (self.wn, text="SNACKS   \n AND    \n CRACKERS   ",font=("Arial",12),bg="#FDFC96")
        self.my_label.place(x=10,y=155)

        self.img7 = Image.open("C:\\store\\lays.jpg")
        self.img7 = self.img7.resize((105,80), Image.ANTIALIAS)
        self.image7 = ImageTk.PhotoImage(self.img7)
        self.label7 = Label(self.wn,image = self.image7,bg="black")
        self.label7.place(x=200,y=140)
        self.lbl7= Label (self.wn, text="      LAYS       \nRs.45 for 42g",font=("Arial",12),bg="#FDFC96")
        self.lbl7.place(x=200,y=225)

        self.img8 = Image.open("C:\\store\\kurkure.jpg")
        self.img8 = self.img8.resize((105,80), Image.ANTIALIAS)
        self.image8 = ImageTk.PhotoImage(self.img8)
        self.label8 = Label(self.wn,image = self.image8,bg="black")
        self.label8.place(x=390,y=140)
        self.lbl8= Label (self.wn, text="  KURKURE  \nRs.150for 80g",font=("Arial",12),bg="#FDFC96")
        self.lbl8.place(x=390,y=225)

        self.img9 = Image.open("C:\\store\\pringles.jpg")
        self.img9 = self.img9.resize((105,80), Image.ANTIALIAS)
        self.image9 = ImageTk.PhotoImage(self.img9)
        self.label9 = Label(self.wn,image = self.image9,bg="black")
        self.label9.place(x=580,y=140)
        self.lbl9= Label (self.wn, text="  PRINGLES \n    Rs.268 / jar ",font=("Arial",12),bg="#FDFC96")
        self.lbl9.place(x=580,y=225)

        self.img10 = Image.open("C:\\store\\monaco.jpg")
        self.img10 = self.img10.resize((105,80), Image.ANTIALIAS)
        self.image10 = ImageTk.PhotoImage(self.img10)
        self.label10 = Label(self.wn,image = self.image10,bg="black")
        self.label10.place(x=770,y=140)
        self.lbl10= Label (self.wn, text="  MONACO   \nRs.80 / Packet",font=("Arial",12),bg="#FDFC96")
        self.lbl10.place(x=770,y=225)

        self.img11 = Image.open("C:\\store\\potato-b.jpg")
        self.img11 = self.img11.resize((105,80), Image.ANTIALIAS)
        self.image11 = ImageTk.PhotoImage(self.img11)
        self.label11 = Label(self.wn,image = self.image11,bg="black")
        self.label11.place(x=960,y=140)
        self.lbl11= Label (self.wn, text="   BISCUIT    \nRs.50 / Packet",font=("Arial",12),bg="#FDFC96")
        self.lbl11.place(x=960,y=225)

        self.img12 = Image.open("C:\\store\\oreo.jpg")
        self.img12 = self.img12.resize((105,80), Image.ANTIALIAS)
        self.image12 = ImageTk.PhotoImage(self.img12)
        self.label12 = Label(self.wn,image = self.image12,bg="black")
        self.label12.place(x=1150,y=140)
        self.lbl12= Label (self.wn, text="      OREO        \n Rs.25 for 5g",font=("Arial",12),bg="#FDFC96")
        self.lbl12.place(x=1150,y=225)

        self.my_label= Label (self.wn, text="     RICE     \n    AND       \n      GRAINS       ",font=("Arial",12),bg="#FDFC96")
        self.my_label.place(x=10,y=290)

        self.img13 = Image.open("C:\\store\\Rice.jpg")
        self.img13 = self.img13.resize((105,80), Image.ANTIALIAS)
        self.image13 = ImageTk.PhotoImage(self.img13)
        self.label13 = Label(self.wn,image = self.image13,bg="black")
        self.label13.place(x=200,y=275)
        self.lbl13= Label (self.wn, text="      RICE       \n  Rs.72 / Kg    ",font=("Arial",12),bg="#FDFC96")
        self.lbl13.place(x=202,y=360)

        self.img14 = Image.open("C:\\store\\maize.jpg")
        self.img14 = self.img14.resize((105,80),Image.ANTIALIAS)
        self.image14 = ImageTk.PhotoImage(self.img14)
        self.label14 = Label(self.wn,image = self.image14,bg="black")
        self.label14.place(x=390,y=275)
        self.lbl14= Label (self.wn, text="     MAIZE        \n Rs.88 / Kg",font=("Arial",12),bg="#FDFC96")
        self.lbl14.place(x=392,y=360)

        self.img15 = Image.open("C:\\store\\peas.jpg")
        self.img15 = self.img15.resize((105,80),Image.ANTIALIAS)
        self.image15 = ImageTk.PhotoImage(self.img15)
        self.label15 = Label(self.wn,image = self.image15,bg="black")
        self.label15.place(x=580,y=275)
        self.lbl15= Label (self.wn, text="      PEAS      \n Rs.183 / Kg ",font=("Arial",12),bg="#FDFC96")
        self.lbl15.place(x=580,y=360)

        self.img16 = Image.open("C:\\store\\dal.jpg")
        self.img16 = self.img16.resize((105,80), Image.ANTIALIAS)
        self.image16 = ImageTk.PhotoImage(self.img16)
        self.label16 = Label(self.wn,image = self.image16,bg="black")
        self.label16.place(x=770,y=275)
        self.lbl16= Label (self.wn, text="  LETENSIL  \n Rs.131 / Kg  ",font=("Arial",12),bg="#FDFC96")
        self.lbl16.place(x=770,y=360)

        self.img17 = Image.open("C:\\store\\rajma.jpg")
        self.img17 = self.img17.resize((105,80), Image.ANTIALIAS)
        self.image17 = ImageTk.PhotoImage(self.img17)
        self.label17 = Label(self.wn,image = self.image17,bg="black")
        self.label17.place(x=960,y=275)
        self.lbl17= Label (self.wn, text="    RAJMA    \n Rs.216 / Kg  ",font=("Arial",12),bg="#FDFC96")
        self.lbl17.place(x=960,y=360)

        self.img18 = Image.open("C:\\store\\chana.jpg")
        self.img18 = self.img18.resize((105,80), Image.ANTIALIAS)
        self.image18 = ImageTk.PhotoImage(self.img18)
        self.label18 = Label(self.wn,image = self.image18,bg="black")
        self.label18.place(x=1150,y=275)
        self.lbl18= Label (self.wn, text="CHICKPEAS \n Rs.108 / Kg  ",font=("Arial",12),bg="#FDFC96")
        self.lbl18.place(x=1150,y=360)

        self.my_label= Label (self.wn, text="     BAKERY     \n    AND       \n      DAIRY       ",font=("Arial",12),bg="#FDFC96")
        self.my_label.place(x=10,y=425)

        self.img19 = Image.open("C:\\store\\bread.jpg")
        self.img19 = self.img19.resize((105,80), Image.ANTIALIAS)
        self.image19 = ImageTk.PhotoImage(self.img19)
        self.label19 = Label(self.wn,image = self.image19,bg="black")
        self.label19.place(x=200,y=410)
        self.lbl19= Label (self.wn, text="     BREAD    \nRs.40/ Packet",font=("Arial",12),bg="#FDFC96")
        self.lbl19.place(x=200,y=495)

        self.img20 = Image.open("C:\\store\\crossiant.jpg")
        self.img20 = self.img20.resize((105,80), Image.ANTIALIAS)
        self.image20 = ImageTk.PhotoImage(self.img20)
        self.label20 = Label(self.wn,image = self.image20,bg="black")
        self.label20.place(x=390,y=410)
        self.lbl20= Label (self.wn, text="      TOAST     \n Rs. 20   / Pcs ",font=("Arial",12),bg="#FDFC96")
        self.lbl20.place(x=390,y=495)

        self.img21 = Image.open("C:\\store\\doughnut.jpg")
        self.img21 = self.img21.resize((105,80), Image.ANTIALIAS)
        self.image21 = ImageTk.PhotoImage(self.img21)
        self.label21 = Label(self.wn,image = self.image21,bg="black")
        self.label21.place(x=580,y=410)
        self.lbl21= Label (self.wn, text="DOUGHNUT\n  Rs.20   / pcs  ",font=("Arial",12),bg="#FDFC96")
        self.lbl21.place(x=580,y=495)

        self.img22 = Image.open("C:\\store\\milk.jpg")
        self.img22 = self.img22.resize((105,80), Image.ANTIALIAS)
        self.image22 = ImageTk.PhotoImage(self.img22)
        self.label22 = Label(self.wn,image = self.image22,bg="black")
        self.label22.place(x=770,y=410)
        self.lbl22= Label (self.wn, text="        MILK       \nRs.76 / Packet",font=("Arial",12),bg="#FDFC96")
        self.lbl22.place(x=770,y=495)

        self.img23 = Image.open("C:\\store\\paneer.jpg")
        self.img23 = self.img23.resize((105,80), Image.ANTIALIAS)
        self.image23 = ImageTk.PhotoImage(self.img23)
        self.label23 = Label(self.wn,image = self.image23,bg="black")
        self.label23.place(x=960,y=410)
        self.lbl23= Label (self.wn, text="   PANEER   \nRs.200/ Packet",font=("Arial",12),bg="#FDFC96")
        self.lbl23.place(x=960,y=495)

        self.img24 = Image.open("C:\\store\\butter.jpg")
        self.img24 = self.img24.resize((105,80), Image.ANTIALIAS)
        self.image24 = ImageTk.PhotoImage(self.img24)
        self.label24 = Label(self.wn,image = self.image24,bg="black")
        self.label24.place(x=1150,y=410)
        self.lbl24= Label (self.wn, text="    BUTTER   \nRs.130/ packet",font=("Arial",12),bg="#FDFC96")
        self.lbl24.place(x=1150,y=495)

        self.my_label= Label (self.wn, text="             \n     BEVERAGES    \n           ",font=("Arial",12),bg="#FDFC96")
        self.my_label.place(x=10,y=545)

        self.img25 = Image.open("C:\\store\\coke.jpg")
        self.img25 = self.img25.resize((105,80), Image.ANTIALIAS)
        self.image25 = ImageTk.PhotoImage(self.img25)
        self.label25 = Label(self.wn,image = self.image25,bg="black")
        self.label25.place(x=200,y=545)
        self.lbl25= Label (self.wn, text="COCACOLA\nRs.115 for 2L ",font=("Arial",12),bg="#FDFC96")
        self.lbl25.place(x=200,y=630)

        self.img26 = Image.open("C:\\store\\fanta.jpg")
        self.img26 = self.img26.resize((105,80), Image.ANTIALIAS)
        self.image26 = ImageTk.PhotoImage(self.img26)
        self.label26 = Label(self.wn,image = self.image26,bg="black")
        self.label26.place(x=390,y=545)
        self.lbl26= Label (self.wn, text="     FANTA     \n Rs.100 for 1L",font=("Arial",12),bg="#FDFC96")
        self.lbl26.place(x=390,y=630)

        self.img27 = Image.open("C:\\store\\soda.jpg")
        self.img27 = self.img27.resize((105,80),Image.ANTIALIAS)
        self.image27 = ImageTk.PhotoImage(self.img27)
        self.label27 = Label(self.wn,image = self.image27,bg="black")
        self.label27.place(x=580,y=545)
        self.lbl27= Label (self.wn, text="       SODA     \nRs.50 for 600ml",font=("Arial",12),bg="#FDFC96")
        self.lbl27.place(x=576,y=630)

        self.img28 = Image.open("C:\\store\\voodka.jpg")
        self.img28 = self.img28.resize((105,80), Image.ANTIALIAS)
        self.image28 = ImageTk.PhotoImage(self.img28)
        self.label28 = Label(self.wn,image = self.image28,bg="black")
        self.label28.place(x=770,y=545)
        self.lbl28= Label (self.wn, text="     VODKA    \nRs.820 for 375ml",font=("Arial",12),bg="#FDFC96")
        self.lbl28.place(x=762,y=630)

        self.img29 = Image.open("C:\\store\\OD.jpg")
        self.img29 = self.img29.resize((105,80), Image.ANTIALIAS)
        self.image29 = ImageTk.PhotoImage(self.img29)
        self.label29 = Label(self.wn,image = self.image29,bg="black")
        self.label29.place(x=960,y=545)
        self.lbl29= Label (self.wn, text="     OLD  DURBAR  \nRs.2900for1000ml",font=("Arial",12),bg="#FDFC96")
        self.lbl29.place(x=948,y=630)

        self.img30 = Image.open("C:\\store\\wine.jpg")
        self.img30 = self.img30.resize((105,80), Image.ANTIALIAS)
        self.image30 = ImageTk.PhotoImage(self.img30)
        self.label30 = Label(self.wn,image = self.image30,bg="black")
        self.label30.place(x=1150,y=545)
        self.lbl30= Label (self.wn, text="    BIG    MASTER   \nRs.750for750ml",font=("Arial",12),bg="#FDFC96")
        self.lbl30.place(x=1136,y=630)

        #adding checkboxes
        self.var1 = IntVar()
        self.checkButton1 = Checkbutton(self.wn, text="", variable = self.var1, onvalue= 1, offvalue=0, bg="#FDFC96")
        self.checkButton1.place(x=175,y=5)
        self.var2 = IntVar()
        self.checkButton2 = Checkbutton(self.wn, text="", variable = self.var2, onvalue= 1, offvalue=0, bg="#FDFC96")
        self.checkButton2.place(x=365,y=5)
        self.var3 = IntVar()
        self.checkButton3 = Checkbutton(self.wn, text="", variable = self.var3, onvalue= 1, offvalue=0, bg="#FDFC96")
        self.checkButton3.place(x=555,y=5)
        self.var4 = IntVar()
        self.checkButton4 = Checkbutton(self.wn, text="", variable = self.var4, onvalue= 1, offvalue=0, bg="#FDFC96")
        self.checkButton4.place(x=745,y=5)
        self.var5 = IntVar()
        self.checkButton5 = Checkbutton(self.wn, text="", variable = self.var5, onvalue= 1, offvalue=0, bg="#FDFC96")
        self.checkButton5.place(x=935,y=5)
        self.var6 = IntVar()
        self.checkButton6 = Checkbutton(self.wn, text="", variable = self.var6, onvalue= 1, offvalue=0, bg="#FDFC96")
        self.checkButton6.place(x=1125,y=5)
        self.var7 = IntVar()
        self.checkButton7 = Checkbutton(self.wn, text="", variable = self.var7, onvalue= 1, offvalue=0, bg="#FDFC96")
        self.checkButton7.place(x=175,y=140)
        self.var8 = IntVar()
        self.checkButton8 = Checkbutton(self.wn, text="", variable = self.var8, onvalue= 1, offvalue=0, bg="#FDFC96")
        self.checkButton8.place(x=365,y=140)
        self.var9 = IntVar()
        self.checkButton9 = Checkbutton(self.wn, text="", variable = self.var9, onvalue= 1, offvalue=0, bg="#FDFC96")
        self.checkButton9.place(x=555,y=140)
        self.var10 = IntVar()
        self.checkButton10 = Checkbutton(self.wn, text="", variable = self.var10, onvalue= 1, offvalue=0, bg="#FDFC96")
        self.checkButton10.place(x=745,y=140)
        self.var11 = IntVar()
        self.checkButton11 = Checkbutton(self.wn, text="", variable = self.var11, onvalue= 1, offvalue=0, bg="#FDFC96")
        self.checkButton11.place(x=935,y=140)
        self.var12 = IntVar()
        self.checkButton12 = Checkbutton(self.wn, text="", variable = self.var12, onvalue= 1, offvalue=0, bg="#FDFC96")
        self.checkButton12.place(x=1125,y=140)
        self.var13 = IntVar()
        self.checkButton13 = Checkbutton(self.wn, text="", variable = self.var13, onvalue= 1, offvalue=0, bg="#FDFC96")
        self.checkButton13.place(x=175,y=275)
        self.var14 = IntVar()
        self.checkButton14 = Checkbutton(self.wn, text="", variable = self.var14, onvalue= 1, offvalue=0, bg="#FDFC96")
        self.checkButton14.place(x=365,y=275)
        self.var15 = IntVar()
        self.checkButton15 = Checkbutton(self.wn, text="", variable = self.var15, onvalue= 1, offvalue=0, bg="#FDFC96")
        self.checkButton15.place(x=555,y=275)
        self.var16 = IntVar()
        self.checkButton16 = Checkbutton(self.wn, text="", variable =self. var16, onvalue= 1, offvalue=0, bg="#FDFC96")
        self.checkButton16.place(x=745,y=275)
        self.var17 = IntVar()
        self.checkButton17 = Checkbutton(self.wn, text="", variable = self.var17, onvalue= 1, offvalue=0, bg="#FDFC96")
        self.checkButton17.place(x=935,y=275)
        self.var18 = IntVar()
        self.checkButton18 = Checkbutton(self.wn, text="", variable = self.var18, onvalue= 1, offvalue=0, bg="#FDFC96")
        self.checkButton18.place(x=1125,y=275)
        self.var19 = IntVar()
        self.checkButton19 = Checkbutton(self.wn, text="", variable = self.var19, onvalue= 1, offvalue=0, bg="#FDFC96")
        self.checkButton19.place(x=175,y=410)
        self.var20 = IntVar()
        self.checkButton20 = Checkbutton(self.wn, text="", variable = self.var20, onvalue= 1, offvalue=0, bg="#FDFC96")
        self.checkButton20.place(x=365,y=410)
        self.var21 = IntVar()
        self.checkButton21 = Checkbutton(self.wn, text="", variable = self.var21, onvalue= 1, offvalue=0, bg="#FDFC96")
        self.checkButton21.place(x=555,y=410)
        self.var22 = IntVar()
        self.checkButton22 = Checkbutton(self.wn, text="", variable = self.var22, onvalue= 1, offvalue=0, bg="#FDFC96")
        self.checkButton22.place(x=745,y=410)
        self.var23 = IntVar()
        self.checkButton23 = Checkbutton(self.wn, text="", variable = self.var23, onvalue= 1, offvalue=0, bg="#FDFC96")
        self.checkButton23.place(x=935,y=410)
        self.var24 = IntVar()
        self.checkButton24 = Checkbutton(self.wn, text="", variable = self.var24, onvalue= 1, offvalue=0, bg="#FDFC96")
        self.checkButton24.place(x=1125,y=410)
        self.var25 = IntVar()
        self.checkButton25 = Checkbutton(self.wn, text="", variable = self.var25, onvalue= 1, offvalue=0, bg="#FDFC96")
        self.checkButton25.place(x=175,y=545)
        self.var26 = IntVar()
        self.checkButton26 = Checkbutton(self.wn, text="", variable = self.var26, onvalue= 1, offvalue=0, bg="#FDFC96")
        self.checkButton26.place(x=365,y=545)
        self.var27 = IntVar()
        self.checkButton27 = Checkbutton(self.wn, text="", variable = self.var27, onvalue= 1, offvalue=0, bg="#FDFC96")
        self.checkButton27.place(x=555,y=545)
        self.var28 = IntVar()
        self.checkButton28 = Checkbutton(self.wn, text="", variable = self.var28, onvalue= 1, offvalue=0, bg="#FDFC96")
        self.checkButton28.place(x=745,y=545)
        self.var29 = IntVar()
        self.checkButton29 = Checkbutton(self.wn, text="", variable = self.var29, onvalue= 1, offvalue=0, bg="#FDFC96")
        self.checkButton29.place(x=935,y=545)
        self.var30 = IntVar()
        self.checkButton30 = Checkbutton(self.wn, text="", variable = self.var30, onvalue= 1, offvalue=0, bg="#FDFC96")
        self.checkButton30.place(x=1125,y=545)


        def popup():
            sql = "INSERT INTO fruit(apple,banana,orange,tomato,spinach,onion,lays,kurkure,pringles,monaco,biscuit,oreo,rice,maize,peas,letensil,rajma,chickpeas,bread,toast,doughnut,milk,paneer,butter,cocacola,fanta,soda,vodka,olddurbar,bigmaster)VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)"
            values=(self.var1.get(),self.var2.get(),self.var3.get(),self.var4.get(),self.var5.get(),self.var6.get(),self.var7.get(),self.var8.get(),self.var9.get(),self.var10.get(),self.var11.get(),self.var12.get(),self.var13.get(),self.var14.get(),self.var15.get(),self.var16.get(),self.var17.get(),self.var18.get(),self.var19.get(),self.var20.get(),self.var21.get(),self.var22.get(),self.var23.get(),self.var24.get(),self.var25.get(),self.var26.get(),self.var27.get(),self.var28.get(),self.var29.get(),self.var30.get())
            self.my_database.add_update_delete(sql, values)
            print(values)
            messagebox.showinfo("Added","Items added to your cart sucessfully!!")

            # Button
        addbutton = PhotoImage(file="C:\\store\\addcart.png")
        add = Button(self.wn, image=addbutton, bd=0, bg='darkblue', fg="white",
                              activebackground="#73C2FB", activeforeground="indigo",
                              font=("Comic Sans MS", 14, "bold"), height=50, cursor="hand2",
                              command=popup, width=150, relief=RIDGE,
                              overrelief=RAISED)
        add.image = addbutton
        add.place(x=10, y=620)



        self.my_database = MyDatabase()
        self.show_menu()
        self.wn.mainloop()

    def logout(self):
            self.wn.destroy()
            from interface.first_window import Firstwindow
            Firstwindow()

    def show_menu(self):
        my_menu = Menu(self.wn)
        self.wn.config(menu=my_menu)
        log_out = Menu(my_menu)
        my_menu.add_cascade(label="Log Out", menu=log_out)
        log_out.add_cascade(label="Log Out", command=self.logout)
